name: "Generate Issues report"
on:
  workflow_dispatch:
    
jobs:
    Rotate_secret:

        strategy:
            fail-fast: false
        
        runs-on: ubuntu-latest 

        steps:
        - uses: actions/checkout@v2
        - uses: bryanmacfarlane/project-reports-action@v1-alpha5
          with: 
            token: ${{ secrets.PROJECT_TOKEN }}
            configPath: IssuesReportConfig.yml
        - uses: bryanmacfarlane/project-reports-action@v1-alpha5
          with: 
            token: ${{ secrets.PROJECT_TOKEN }}
            configPath: EpicIssuesReportConfig.yml
        - uses: bryanmacfarlane/project-reports-action@v1-alpha5
          with: 
            token: ${{ secrets.PROJECT_TOKEN }}
            configPath: AzureIntegrationReportConfig.yml
        - run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHubAction" 
            git pull
            git add ./_reports
            git commit -m "adding reports"
            git push origin main      
            
            
            
